### ISSUE TITLE
Inherited item selector field issues

### ISSUE THREAD

**Issue by rart** [craftersoftware/craftercms#6540]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] The issue is in the develop branch
- [X] The issue is in the latest released 4.1.x
- [ ] The issue is in the latest released 4.0.x
- [ ] The issue is in the latest released 3.1.x

### Describe the issue

An item selector field that comes into the model by inheritance — that's not declared on the page model, only on the level descriptor — renders correctly, and some features work correctly, but some other features present issues. See detailed list of issues below.

**Note**: Many of these issues are likely to be intertwined in their code fix so this needs to be kept a single ticket.

### Steps to reproduce

**Shortcut**: Create site from https://github.com/rart/editorial-6540.git and jump to step # 5. Read steps 1-4 for context.

**Detailed base steps**
1. Create site from Editorial
2. Copy the `features_o` and its `featuresComponents` datasource and add it to the level descriptor renaming `features_o` to `features2_o`
3. Open `/site/website/index.xml`, cut the "Closed captioning" feature from `features_o` on home to `features2_o` on the level descriptor `/site/website/crafter-level-descriptor.level.xml`
4. Render the `features2_o` on  `home.ftl` right below the `features_o` section
5. See issues below for next steps for each issue
    - Trying to delete a shared item from the inherited field produces an error
      - Click on the item and press the rubbish bin, or drag and drop on the floating bin and observe the error on the browser console
    - Drag/dropping a new component into the inherited field, works but leaves the **inheritance target** item locked
      - Click on the right sidebar "Add components" panel and a feature to the `features2_o` field
      - Notice Home remains locked
    - Move mode doesn't present any highlighting around the items of the inherited item selector
      - Click on the move mode switch button (or press m) to enter move mode
      - Hover around the `features2_o` section
      - Notice there's no highlight
    - Edit mode highlights and allows editing but drag & drop doesn't work (no errors, just doesn't start the drag)
      - On base edit mode, try to drag & drop the features on the `features2_o` section
      - Notice the drag has no effect
    - The zone menu when the inherited field is selected doesn't show move up/down options
      -  Click on one feature on `features2_o`, notice up/down arrows are not shown
    - Attempting to move a feature from the model's own field to the inherited field results in 
      - Strange locking behaviours: Embedded components show locked with no way of unlocking
      - Shared components seem to work fine but reloading reveals the operation didn't actually work

### Relevant log output

```
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at value (craftercms-xb.umd.js:19827:34)
    at deleteItem (craftercms-xb.umd.js:24476:93)
    at Object.next (craftercms-xb.umd.js:54884:13)
    at ConsumerObserver.next (craftercms-xb.umd.js:17411:27)
    at Subscriber._next (craftercms-xb.umd.js:17381:24)
    at Subscriber.next (craftercms-xb.umd.js:17358:14)
    at Subscriber._next (craftercms-xb.umd.js:17381:24)
    at Subscriber.next (craftercms-xb.umd.js:17358:14)
    at craftercms-xb.umd.js:19048:29
    at OperatorSubscriber._this._next (craftercms-xb.umd.js:17632:11)
```

**Comment by russdanner** [comment]
Confirmed
